import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../styles/globals.css";
import type { PropsWithChildren } from "react";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={outfit.variable}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
